2.13 cosmetique front end
vrn-sh/erp pull request #106
Opened 2023-04-11 07:03 UTC by Loris-Reggiani

# Description

Page de type Erreur 404
Ajouter au routeur du front la nouvelle page 404
Ajout d’un form de contact dans la page d'accueil

2023-04-11 07:11 UTC, bogdzn reviewed
Looks OK to me, @claraxuxu can you confirm CSS & Components are compliant with Figma pages ?

2023-04-11 07:47 UTC, claraxuxu commented on web/src/pages/Error/Error.tsx
> +    console.log('Not Found');
cette ligne peut être enlevée

2023-04-11 07:50 UTC, claraxuxu requested changes
Possible d'ajouter la partie contact dans la nav bar dans le fichier NavBar.tsx stp (comme "home" "Team" machin...) Merci!

2023-04-11 07:51 UTC, claraxuxu commented
Sinon le reste semble ok pour moi aussi ;)

2023-04-12 07:02 UTC, claraxuxu approved these changes

2023-04-12 07:05 UTC, merged