Register to mailing list
vrn-sh/erp pull request #373
Opened 2023-11-17 12:48 UTC by Loris-Reggiani

# Description

Adding the new backend route: {{baseUrl}}/mailing-list
this route stores emails to our newsletter
you can test the route using: python3 manage.py test api.tests.mailingList_test in api folder there are several tests

Adding front wise a checkbox above the ContactForm
it will add the email in Voron's newsletter using the new mailing route

2023-11-22 16:57 UTC, claraxuxu commented
pourquoi cette branch contient aussi les changements de l'autre pr?

2023-11-23 01:44 UTC, Loris-Reggiani commented
> pourquoi cette branch contient aussi les changements de l'autre pr?

je pense que c'est parce que j'avais créer cette branche là au dessus de l'autre, mais normalement c'est fix (j'ai pris le login.tsx du next

2023-12-01 22:50 UTC, claraxuxu requested changes
- [ ] cette pr contient aussi les changements de reset mdp, la partie contact form a été changé, il est sensé être annulé vu que Marianne nous recommande de le faire dans footer
- [ ] Est-ce que tu peux check côté back stp @djnnvx ? Merci d'avance! :)

2023-12-02 22:45 UTC, djnnvx requested changes
you need to create the migration file as well:

https://docs.djangoproject.com/en/4.2/howto/writing-migrations/

2023-12-02 22:45 UTC, djnnvx commented on api/api/models/mailingList.py
> +from django.db import models
les noms de fichiers doivent etre en snake_case

2023-12-02 22:45 UTC, djnnvx commented on api/api/serializers/mailingList.py
> +        if not value or "@" not in value:
this is pointless, you dont need to add this function

2023-12-02 22:45 UTC, djnnvx commented on api/api/serializers/mailingList.py
> +        if not value or "@" not in value:
this file should be in snake_case too

2023-12-02 22:45 UTC, djnnvx commented on api/core/urls.py
> +from api.views.viewsets.mailingList import MailingListViewset
this file doesn't exist

2023-12-02 22:45 UTC, djnnvx commented on api/core/urls.py
> +router.register(r'mailing-list', MailingListViewset)
this class doesn't exist

2023-12-02 22:45 UTC, djnnvx commented on web/src/pages/Reset/Reset.tsx
> +    console.log(token);
why is this here ?

2023-12-21 15:13 UTC, djnnvx reviewed
looks OK for back-end. @claraxuxu can you approve if this is OK for front-end too ?

2023-12-26 16:44 UTC, claraxuxu approved these changes

2023-12-26 16:44 UTC, claraxuxu commented on api/core/urls.py
> +    path('reset', ResetPasswordView.as_view(), name='reset_password'),
changement de pr reset mdp

2023-12-26 16:44 UTC, claraxuxu commented on web/src/pages/Home/Form/ContactForm.tsx
cette partie ne doit pas être modifié

2023-12-26 16:44 UTC, claraxuxu commented on web/src/pages/Login/Login.tsx
> +        if (email !== '') {
pk changer cette condition?

2023-12-26 16:44 UTC, claraxuxu commented on web/src/pages/Reset/Reset.tsx
changement de pr reset mdp

2023-12-26 16:56 UTC, djnnvx approved these changes

2023-12-26 16:56 UTC, merged