[3JH] Live documentation for saas loader page #332
vrn-sh/erp pull request #380
Opened 2023-12-04 11:55 UTC by Loris-Reggiani

# Description

This is a static page that explains how to use the saas page, with screenshots and examples, so that user easily understand what they should do.

# Changes include

- [ ] Accueil.tsx
- [ ] Generated payload.gif

2023-12-26 17:35 UTC, djnnvx commented
@Loris-Reggiani there is a conflict in Acceuil.tsx. Can you please fix ? Thank you

2023-12-27 12:57 UTC, djnnvx commented
![image](https://github.com/vrn-sh/erp/assets/29751352/c62d7f56-ca41-4f57-ae04-b1151fe01d0e)

there are still conflicts

2024-01-03 16:58 UTC, claraxuxu requested changes

2024-01-03 16:58 UTC, claraxuxu commented on web/src/assets/BasicShellcode.gif
Can you zoom the website in a normal size to better show the steps please? thx

2024-01-03 16:58 UTC, claraxuxu commented on web/src/assets/Generate payload.gif
same here

2024-01-03 16:58 UTC, claraxuxu commented on yarn.lock
this should not be pushed

2024-01-13 21:09 UTC, closed without merging