18 set up front end ci
vrn-sh/erp pull request #58
Opened 2023-02-15 15:46 UTC by TheOrionsB

# Description

Set up Continuous Integration (CI) for the frontend

# Fixes

- fixes #18 

# Changes include

- [x] New feature | Breaking: ESLint is set up with the airbnb and airbnb-typescript configuration
- [x] New feature: Prettier is set up.
- [x] New feature: vitest is set up and its related folders and files are created.

# Breaking changes

The linter configuration can reject PRs once the github action is set up. The code need to be fixed according to ESLint and prettier to pass.

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added @vrn-sh/members to the reviewers, or specific members of the team
- [x] I have added the needed labels
- [x] I have tested this code
- [x] I have added / updated tests (unit / functionals / end-to-end / ...)
- [x] I have updated the README and other relevant documents (guides...)

# Additional comments

Will need @bogdzn to set up the github workflow that runs the linter and tests on pull requests

2023-02-15 17:13 UTC, TheOrionsB commented
Finally, done. Sorry for all the commits. Couldn't figure out how to test the Github actions without pushing.
Linting fails as it's supposed to considering the codebase is not yet compliant with the linter.

2023-02-16 01:35 UTC, bogdzn requested changes
Couple things are missing, but overall good PR. Let's have a call tomorrow night for the missing CI.

2023-02-16 01:35 UTC, bogdzn commented on .github/workflows/frontend-lint.yml
> +        node-version: [14.x, 16.x, 18.x]
Current `node` maintained version is `14.18`. Please see [tool-versions](https://github.com/vrn-sh/erp/blob/18-set-up-front-end-ci/.tool-versions) & [asdf](https://asdf-vm.com/guide/getting-started.html) for more info

2023-02-16 01:35 UTC, bogdzn commented on .github/workflows/frontend-unit-tests.yml
> +        node-version: [14.x, 16.x, 18.x]
Same here, version 16.x and 18.x are unneeded

2023-02-16 01:35 UTC, bogdzn commented on web/.eslintrc.cjs
> +module.exports = {
Please exclude `dist/` folder

2023-02-18 13:13 UTC, TheOrionsB commented
safe to be merged:
Team.tsx linter errors while be fixed when #43  will be merged

2023-02-18 13:14 UTC, bogdzn approved these changes

2023-02-18 13:16 UTC, merged