API Authentication Integration (Login & Register)
vrn-sh/erp pull request #94
Opened 2023-03-16 16:19 UTC by blacky-yg

# Description

Please provide a detailed description of what was done in this PR.
Precise the issue that you are resolving.

# Fixes

Specify which issue this PR targets, like so:

- fixes #24 

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it.

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added @vrn-sh/members to the reviewers, or specific members of the team
- [ ] I have added the needed labels
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

2023-03-17 09:36 UTC, bogdzn requested changes
Having CORS configuration set with any Host is a security issue. I can fix this if you don't have the time, but we should not merge this until it is fixed.

2023-03-17 09:36 UTC, bogdzn commented on api/core/settings.py
> +ALLOWED_HOSTS=['*']
This is very dangerous. Using `'*'` as allowed hosts is only OK for Local development, I can fix this in this branch if that is ok for you @blacky-yg ?

2023-03-17 09:36 UTC, bogdzn commented on web/.env.example
It could be good to rename this to `env-dist`, like the one used for the API.

2023-03-19 12:45 UTC, bogdzn commented
ok to review @claraxuxu

2023-03-19 12:45 UTC, bogdzn approved these changes

2023-03-19 12:56 UTC, bogdzn approved these changes

2023-03-20 13:47 UTC, claraxuxu approved these changes

2023-03-20 13:49 UTC, merged

2023-03-20 13:50 UTC, bogdzn commented
good work @blacky-yg